####################################################################
# Census Getter Properties
####################################################################



# Census API Settings
# ------------------------------------------------------------------

# State, Counties & Year to get ACS data. Will use 5 year ACS by default. 
state: 53
counties: ['035', '033', '053', '061']
census_year: 2016
tract: None
# Must create Env Variable holding census key. Put name of Var here:
census_key: CENSUS_KEY

controls_expression_file: census_getter_expressions.csv
apply_acs_shares_expression_file: ofm_shares.csv

# Relate block groups with tracts
hh_bg_size_attr: "B11001_001E"
hh_tract_size_attr: "B08201_001E"
pers_bg_size_attr: "B01001_001E"
pers_tract_size_attr: "B01003_001E"


# Local Data
# ------------------------------------------------------------------
# Provide non-Census data for use in expression files
data_dir: data

input_table_list:
  - tablename: ofm_control_totals
    filename : ofm_control_totals.csv
  - tablename: hh_size_control_totals
    filename: hh_size_control_totals.csv

# For local data, fill NaN values; use None to leave NaNs
nan_fill: 0


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - all_acs
    - combined_acs
    - all_input_data
    - ofm_controls


# Steps for base mode
# ------------------------------------------------------------------
run_list:
  steps:
    - input_pre_processor
    - get_acs_data
    - apply_acs_shares
    - write_tables